# Generated by Django 6.0.7 on 2026-09-14 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('marketplace', '0002_orderitem_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='municipality',
            field=models.ForeignKey(blank=True, help_text='Marketplace location (municipality associated with this product/supplier)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='locations.municipality'),
        ),
    ]
