# Generated by Django 5.2.16 on 2026-07-26 10:11

import django.db.models.deletion
import permits.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=permits.models.generate_reference_number, editable=False, max_length=50, unique=True)),
                ('application_type', models.CharField(choices=[('NEW_CONSTRUCTION', 'New Residential Building Construction'), ('RENOVATION', 'Building Renovation'), ('EXTENSION', 'Building Extension / Storey Addition')], default='NEW_CONSTRUCTION', max_length=30)),
                ('tole_address', models.CharField(help_text='Tole or Street Address', max_length=255)),
                ('plot_number', models.CharField(help_text='Kitta Number', max_length=100)),
                ('land_area_sqft', models.DecimalField(decimal_places=2, help_text='Land Area in Sq. Ft.', max_digits=10)),
                ('total_built_up_area_sqft', models.DecimalField(decimal_places=2, help_text='Proposed Built-up Area in Sq. Ft.', max_digits=10)),
                ('storeys_count', models.PositiveIntegerField(default=1, help_text='Number of Storeys')),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='Estimated Construction Cost (NPR)', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Technical Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('remarks', models.TextField(blank=True, help_text='Officer notes or feedback', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_applications', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_applications', to='locations.municipality')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_applications', to='locations.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BLUEPRINT', 'Architectural / Structural Blueprint'), ('CITIZENSHIP', 'Citizenship Certificate Copy'), ('LALPURJA', 'Land Ownership Certificate (Lalpurja)'), ('TAX_CLEARANCE', 'Property Tax Clearance Receipt'), ('OTHER', 'Other Supporting Document')], default='BLUEPRINT', max_length=30)),
                ('title', models.CharField(help_text='Brief descriptive title of the document', max_length=200)),
                ('file', models.FileField(upload_to='permit_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='permits.permitapplication')),
            ],
        ),
        migrations.CreateModel(
            name='PermitDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Technical Review')], max_length=30)),
                ('remarks', models.TextField(help_text='Detailed officer justification / inspection feedback')),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='permits.permitapplication')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-decision_date'],
            },
        ),
    ]
