# Generated by Django 6.0.7 on 2026-09-14 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permitapplication',
            name='completion_certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated_documents/completion_certificates/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='permitapplication',
            name='completion_remarks',
            field=models.TextField(blank=True, help_text='Final inspection notes or completion remarks', null=True),
        ),
        migrations.AddField(
            model_name='permitapplication',
            name='completion_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_permits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permitapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Technical Review'), ('APPROVED', 'Approved'), ('CONSTRUCTION_ONGOING', 'Construction Ongoing'), ('COMPLETION_PENDING', 'Completion Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='ConstructionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Officer inspection remarks', null=True)),
                ('generated_approval_pdf', models.FileField(blank=True, null=True, upload_to='generated_documents/phase_approvals/%Y/%m/')),
                ('generated_stamped_blueprint', models.FileField(blank=True, null=True, upload_to='generated_documents/stamped_blueprints/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_phases', to='permits.permitapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_construction_phases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('application', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='ConstructionPhaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BLUEPRINT', 'Architectural / Structural Blueprint'), ('SITE_PHOTO', 'Site Construction Photo'), ('INSPECTION_REPORT', 'Field Inspection Report'), ('COMPLETION_REPORT', 'Phase Completion Report'), ('OTHER', 'Other Supporting Document')], default='BLUEPRINT', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='construction_phases/original/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='permits.constructionphase')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
