# Generated by Django 6.0.7 on 2026-09-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_permitapplication_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='permit_approval_letter_pdf',
            field=models.FileField(blank=True, null=True, upload_to='generated_documents/permit_approval_letters/%Y/%m/'),
        ),
    ]
