# Generated by Django 5.2.4 on 2026-08-12 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication & JWT'), ('PERMIT', 'Building Permits & Inspections'), ('PAYMENT', 'eSewa Payments'), ('MARKETPLACE', 'Marketplace & Orders'), ('ADMIN', 'System Administration')], default='AUTH', max_length=30)),
                ('actor_username', models.CharField(blank=True, help_text='Stored username in case user is deleted or unauthenticated', max_length=150)),
                ('action', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
