# Generated by Django 5.2.4 on 2026-09-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short personal or business description.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nid_document',
            field=models.ImageField(blank=True, help_text='Uploaded NID/Citizenship card image for identity verification.', null=True, upload_to='nid_documents/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nid_verified',
            field=models.BooleanField(default=False, help_text='True when the uploaded NID image OCR matched the manually entered citizenship number.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='citizenship_number',
            field=models.CharField(blank=True, help_text='National ID / Citizenship number — verified via NID document OCR.', max_length=50, null=True),
        ),
    ]
