# Generated by Django 5.2.16 on 2026-07-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.PositiveIntegerField(help_text='Province Number (1 to 7)', unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('METROPOLITAN', 'Metropolitan City'), ('SUB_METROPOLITAN', 'Sub-Metropolitan City'), ('MUNICIPALITY', 'Municipality'), ('RURAL_MUNICIPALITY', 'Rural Municipality (Gaunpalika)')], default='MUNICIPALITY', max_length=30)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='locations.district')),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.province'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('province', 'name')},
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.PositiveIntegerField()),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='locations.municipality')),
            ],
            options={
                'ordering': ['ward_number'],
                'unique_together': {('municipality', 'ward_number')},
            },
        ),
    ]
